CREATE TABLE testboard(
  uid int unsigned AUTO_INCREMENT,
  gid int unsigned DEFAULT 0,
  level int unsigned DEFAULT 0,
  depth varchar(255) DEFAULT 'A',
  subject varchar(255) NOT NULL,
  companyname varchar(20) NOT NULL,
  future varchar(50),
  homepage varchar(50),
  location varchar(50),
  industries varchar(50),
  contract varchar(50),
  salary varchar(50),
  requirement text NOT NULL,
  description text NOT NULL,
  writedate char(10),
  refnum int unsigned DEFAULT 0,
  PRIMARY KEY (uid),
);
